---
global:
  slack_api_url: ${SLACK_URL}
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'web.hook'
  match_timeout: 10m
  match_config_interval: 1m
receivers:
  - name: 'web.hook'
    slack_configs:
      - channel: '#idva-dev'
        text: |
          Environment: ${ENVIRONMENT_NAME}
          Summary: {{ .CommonAnnotations.summary }}
          Description: {{ .CommonAnnotations.description }}
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
