---
global:
  slack_api_url: ${SLACK_URL}
route:
  group_by: ['...']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'web.hook'
receivers:
  - name: 'web.hook'
    slack_configs:
        text: |
          Summary: {{ .CommonAnnotations.summary }}
          {{ .CommonAnnotations.description }}
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
