---
applications:
  - name: alerts
    routes:
      - route: identity-idva-monitoring-alerts-((ENVIRONMENT_NAME)).apps.internal
    memory: 64MB
    instances: 2
    buildpacks:
      - binary_buildpack
    command: source start-alertmanager.sh
    env:
      SLACK_URL: ((SLACK_URL))
      ENVIRONMENT_NAME: ((ENVIRONMENT_NAME))
