---
applications:
  - name: alertmanager
    routes:
      - route: identity-idva-monitoring-alertmanager-((ENVIRONMENT_NAME)).apps.internal
    memory: 64MB
    instances: 2
    buildpacks:
      - binary_buildpack
    command: |
      ./create_web_config.sh && \
      ./alertmanager --web.listen-address="0.0.0.0:$PORT" \
          --cluster.peer="identity-idva-monitoring-alertmanager-((ENVIRONMENT_NAME)).apps.internal:9094" \
          --web.config.file=web-config.yml \
          --web.external-url https://identity-idva-monitoring-alertmanager-((ENVIRONMENT_NAME)).apps.internal/
    env:
      SLACK_URL: ((SLACK_URL))
      ENVIRONMENT_NAME: ((ENVIRONMENT_NAME))
