---
applications:
  - name: monitoring
    routes:
      - route: identity-idva-monitoring-((ENVIRONMENT_NAME)).apps.internal
    memory: ((MEMORY))
    instances: ((INSTANCES))
    buildpacks:
      - binary_buildpack
    processes:
      - type: web
        command: |
          ./install_prometheus.sh && \
          ./create_web_config.sh && \
          ./prometheus --web.listen-address="0.0.0.0:$PORT" --storage.tsdb.retention.size="950MB" --web.config.file=web-config.yml
