---
applications:
  - name: prometheus
    routes:
      - route: identity-idva-monitoring-prometheus-((ENVIRONMENT_NAME)).apps.internal
    memory: ((MEMORY))
    instances: ((INSTANCES))
    buildpacks:
      - https://github.com/cloudfoundry/apt-buildpack
      - binary_buildpack
    command: |
      # Use 'source' to prevent creating a new shell process for 'run.sh'
      source run.sh
    env:
      ENVIRONMENT_NAME: ((ENVIRONMENT_NAME))
