---
global:
  # The labels to add to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    cluster: idva-prometheus
    __replica__: replica-${CF_INSTANCE_INDEX}

# Alertmanager configuration
alerting:
  alert_relabel_configs:
    - action: labeldrop
      regex: __replica__
  alertmanagers:
    - dns_sd_configs:
        - names:
            - 'identity-idva-monitoring-alertmanager-${ENVIRONMENT_NAME}.apps.internal'
          type: 'A'
          port: 8080
      tls_config:
        insecure_skip_verify: true
      scheme: https

# Load rules once and periodically evaluate them according to the
# global 'evaluation_interval'.
rule_files:
  - "rules.yml"

remote_write:
  - url: https://identity-idva-monitoring-cortex-${ENVIRONMENT_NAME}.apps.internal:8080/api/v1/push
    tls_config:
      insecure_skip_verify: true

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped
  # from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:8080']
    scheme: https
    tls_config:
      insecure_skip_verify: true

  - job_name: 'dns-discovery-kong'
    dns_sd_configs:
      - names:
          - 'identity-idva-kong-${ENVIRONMENT_NAME}.apps.internal'
        type: 'A'
        port: 8100
    scheme: https
    tls_config:
      insecure_skip_verify: true

  - job_name: 'dns-discovery-cf-metrics'
    dns_sd_configs:
      - names:
          - 'identity-idva-cf-metrics-${ENVIRONMENT_NAME}.apps.internal'
        type: 'A'
        port: 8080
    scheme: https
    tls_config:
      insecure_skip_verify: true

  - job_name: 'dns-discovery-grafana'
    dns_sd_configs:
      - names:
          - 'identity-idva-monitoring-grafana-${ENVIRONMENT_NAME}.apps.internal'
        type: 'A'
        port: 8080
    scheme: https
    tls_config:
      insecure_skip_verify: true

  - job_name: 'dns-redis-exporter'
    dns_sd_configs:
      - names:
          - 'identity-idva-metrics-redis-${ENVIRONMENT_NAME}.apps.internal'
        type: 'A'
        port: 8080
    scheme: https
    tls_config:
      insecure_skip_verify: true

  - job_name: 'dns-elasticsearch-exporter'
    dns_sd_configs:
      - names:
          - 'identity-idva-metrics-elasticsearch-${ENVIRONMENT_NAME}.apps.internal'
        type: 'A'
        port: 8080
    scheme: http
