---
global:
  # The labels to add to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    cluster: idva-prometheus
    __replica__: replica-${CF_INSTANCE_INDEX}

# Alertmanager configuration
alerting:
  alert_relabel_configs:
    - action: labeldrop
      regex: __replica__
    - action: labeldrop
      regex: instance

  alertmanagers:
    - scheme: https
      static_configs:
        - targets: ['identity-idva-monitoring-alertmanager-${ENVIRONMENT_NAME}.apps.internal:61443']

# Load rules once and periodically evaluate them according to the
# global 'evaluation_interval'.
rule_files:
  - "rules.yml"

remote_write:
  - url: https://identity-idva-monitoring-cortex-${ENVIRONMENT_NAME}.apps.internal:61443/api/v1/push

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped
  # from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:8080']
    scheme: http

  - job_name: 'dns-discovery-kong'
    dns_sd_configs:
      - names:
          - 'identity-idva-kong-${ENVIRONMENT_NAME}.apps.internal'
        type: 'A'
        port: 8100
    scheme: https
    tls_config:
      insecure_skip_verify: true

  - job_name: 'cf-metrics'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['identity-idva-cf-metrics-${ENVIRONMENT_NAME}.apps.internal:61443']

  - job_name: 'grafana'
    scheme: https
    static_configs:
      - targets: ['identity-idva-monitoring-grafana-${ENVIRONMENT_NAME}.apps.internal:61443']

  - job_name: 'watchtower'
    scheme: https
    static_configs:
      - targets: ['identity-idva-monitoring-watchtower-${ENVIRONMENT_NAME}.apps.internal:61443']

  - job_name: 'redis-exporter'
    scheme: https
    static_configs:
      - targets: ['identity-idva-metrics-redis-${ENVIRONMENT_NAME}.apps.internal:61443']

  - job_name: 'elasticsearch-exporter'
    scheme: https
    static_configs:
      - targets: ['identity-idva-metrics-elasticsearch-${ENVIRONMENT_NAME}.apps.internal:61443']

  - job_name: 'alertmanager'
    scheme: https
    static_configs:
      - targets: ['identity-idva-monitoring-alertmanager-${ENVIRONMENT_NAME}.apps.internal:61443']
