---
global:

# Alertmanager configuration
alerting:
  alertmanagers:
    - dns_sd_configs:
        - names:
            - 'identity-idva-monitoring-alertmanager-${ENVIRONMENT_NAME}.apps.internal'
          type: 'A'
          port: 8080
      tls_config:
        insecure_skip_verify: true
      scheme: https

# Load rules once and periodically evaluate them according to the
# global 'evaluation_interval'.
rule_files:
  - "rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped
  # from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:8080']
    scheme: https
    tls_config:
      insecure_skip_verify: true

  - job_name: 'dns-discovery-kong'
    dns_sd_configs:
      - names:
          - 'identity-idva-kong-${ENVIRONMENT_NAME}.apps.internal'
        type: 'A'
        port: 8100
    scheme: https
    tls_config:
      insecure_skip_verify: true

  - job_name: 'dns-discovery-cf-metrics'
    dns_sd_configs:
      - names:
          - 'identity-idva-cf-metrics-${ENVIRONMENT_NAME}.apps.internal'
        type: 'A'
        port: 8080
    scheme: https
    tls_config:
      insecure_skip_verify: true

  - job_name: 'dns-discovery-grafana'
    dns_sd_configs:
      - names:
          - 'identity-idva-monitoring-grafana-${ENVIRONMENT_NAME}.apps.internal'
        type: 'A'
        port: 8080
    scheme: https
    tls_config:
      insecure_skip_verify: true
