---
global:
  port: ${PORT}
  cloud_controller_url: https://api.fr.cloud.gov
  refresh_interval: 5m
apps:
  enabled: true
  resources:
    - name: alertmanager
      routes:
        - identity-idva-monitoring-alertmanager-${ENVIRONMENT_NAME}.apps.internal
    - name: cf-metrics
      routes:
        - identity-idva-cf-metrics-${ENVIRONMENT_NAME}.apps.internal
    - name: cortex
      routes:
        - identity-idva-monitoring-cortex-${ENVIRONMENT_NAME}.apps.internal
    - name: cron
    - name: elasticsearch-metrics
      routes:
        - identity-idva-metrics-elasticsearch-${ENVIRONMENT_NAME}.apps.internal
    - name: eph-es
      optional: true
      routes:
        - idva-eph-es-${ENVIRONMENT_NAME}.apps.internal
    - name: eph-kibana
      optional: true
    - name: es-proxy
      routes:
        - identity-idva-es-proxy-${ENVIRONMENT_NAME}.apps.internal
    - name: grafana
      routes:
        - identity-idva-monitoring-grafana-${ENVIRONMENT_NAME}.apps.internal
    - name: kong
      routes:
        - identity-idva-kong-${ENVIRONMENT_NAME}.apps.internal
        - idva-api-${ENVIRONMENT_NAME}.app.cloud.gov
        - idva-${ENVIRONMENT_NAME}.app.cloud.gov
        - idva-keycloak-${ENVIRONMENT_NAME}.app.cloud.gov
        - idva-sdk-${ENVIRONMENT_NAME}.app.cloud.gov
        - idva-portal-${ENVIRONMENT_NAME}.app.cloud.gov
        - idva-marmot-${ENVIRONMENT_NAME}.app.cloud.gov
    - name: kong-egress
      routes:
        - idva-kong-egress-${ENVIRONMENT_NAME}.apps.internal
    - name: kong-internal
      routes:
        - idva-kong-internal-${ENVIRONMENT_NAME}.apps.internal
    - name: locust
      optional: true
    - name: outbound-proxy
      optional: true
      routes:
        - outbound-proxy-${ENVIRONMENT_NAME}.apps.internal
    - name: prometheus
      routes:
        - identity-idva-monitoring-prometheus-${ENVIRONMENT_NAME}.apps.internal
    - name: redis-metrics
      routes:
        - identity-idva-metrics-redis-${ENVIRONMENT_NAME}.apps.internal
    - name: sk-analytics
    - name: sk-api
      routes:
        - identity-idva-sk-api-${ENVIRONMENT_NAME}.apps.internal
    - name: sk-authenticid
    - name: sk-challenge
    - name: sk-credential
    - name: sk-dbconfigs
    - name: sk-devicepolicy
    - name: sk-esconfigs
    - name: sk-events
    - name: sk-events-read
    - name: sk-ews
    - name: sk-fido
    - name: sk-flow
    - name: sk-functions
    - name: sk-http
    - name: sk-iovation
    - name: sk-jumio
    - name: sk-lexisnexis
    - name: sk-manifest
    - name: sk-mfacontainer
    - name: sk-node
    - name: sk-oe
    - name: sk-onfido
    - name: sk-openid
    - name: sk-portal
      routes:
        - idva-sk-portal-${ENVIRONMENT_NAME}.apps.internal
    - name: sk-sdk
      routes:
        - idva-sk-sdk-${ENVIRONMENT_NAME}.apps.internal
    - name: sk-smtp
    - name: sk-socure
    - name: sk-totp
    - name: sk-transunion
    - name: sk-transunion-tloxp
    - name: sk-userpolicy
    - name: sk-variables
    - name: sk-webhook
    - name: static-assets
      routes:
        - identity-idva-static-assets-${ENVIRONMENT_NAME}.app.cloud.gov
    - name: watchtower
      routes:
        - identity-idva-monitoring-watchtower-${ENVIRONMENT_NAME}.apps.internal
    - name: gdrive
    - name: id-filter
    - name: incode
    - name: qualtrix
    - name: s3-interface
    - name: sk-clear
    - name: sk-generic
    - name: sk-samlidp
    - name: token

spaces:
  enabled: true
  resources:
    - name: ${ENVIRONMENT_NAME}
      allow_ssh: false
    - name: ${ENVIRONMENT_NAME}-public
      allow_ssh: false
    - name: ${ENVIRONMENT_NAME}-closed
      allow_ssh: false
    - name: ${ENVIRONMENT_NAME}-warpgate
      allow_ssh: true
