---
apps:
  enabled: true
  resources:
    - name: alertmanager
    - name: cf-metrics
    - name: cortex
    - name: elasticsearch-metrics
    - name: es-proxy
    - name: gpo
      optional: true
    - name: grafana
    - name: kibana
    - name: kong
    - name: locust
      optional: true
    - name: outbound-proxy
      optional: true
    - name: prometheus
    - name: redis-metrics
    - name: sk-analytics
    - name: sk-api
    - name: sk-challenge
    - name: sk-credential
    - name: sk-dbconfigs
    - name: sk-devicepolicy
    - name: sk-esconfigs
    - name: sk-events
    - name: sk-events-read
    - name: sk-ews
    - name: sk-fido
    - name: sk-flow
    - name: sk-functions
    - name: sk-http
    - name: sk-iovation
    - name: sk-jumio
    - name: sk-lexisnexis
    - name: sk-manifest
    - name: sk-mfacontainer
    - name: sk-node
    - name: sk-oe
    - name: sk-openid
    - name: sk-portal
    - name: sk-sdk
    - name: sk-smtp
    - name: sk-socure
    - name: sk-totp
    - name: sk-transunion
    - name: sk-userpolicy
    - name: sk-variables
    - name: sk-webhook
    - name: static-assets
    - name: usps
      optional: true
    - name: watchtower
spaces:
  enabled: true
  resources:
    - name: dev
      allow_ssh: true
    - name: test
      allow_ssh: true
    - name: prod
      allow_ssh: false
