---
apiVersion: 1

datasources:
  - name: idva-cortex-data
    type: prometheus
    access: proxy
    url: https://identity-idva-monitoring-prometheus-${ENVIRONMENT_NAME}.apps.internal:$PORT/api/prom/
    isDefault: false
    editable: false
    jsonData:
      tlsSkipVerify: true
