---
apiVersion: 1

datasources:
  - name: idva-monitoring-data
    type: prometheus
    access: proxy
    url: https://identity-idva-monitoring-prometheus-${ENVIRONMENT_NAME}.apps.internal:61443
    isDefault: true
    editable: false
    jsonData:
      tlsSkipVerify: true
