---

name: Deploy analytics scripting

on:
  workflow_call:
    secrets:
      CF_USERNAME:
        required: true
      CF_PASSWORD:
        required: true
      CF_ORG:
        required: true

jobs:
  deploy:
    if: github.repository_owner == '18F'
    name: deploy-analytics-manifest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: 18F/identity-idva-cf-setup@v2
        id: cf-setup
        with:
          cf-username: ${{ secrets.CF_USERNAME }}
          cf-password: ${{ secrets.CF_PASSWORD }}
          cf-org: ${{ secrets.CF_ORG }}

      - name: Deploy analytics as task
        run: |
          cd kibana/analytics-scripting
          cf push --task
