---
# The check-config workflow will run the Prometheus 'promtool check config'
# command to validate the configuration file.
name: Check-Config

on:
  pull_request:
    paths:
      - '**/prometheus-config.yml'

jobs:
  check-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate config
        run: |
          envsubst < prometheus/prometheus-config.yml > prometheus/prometheus.yml
        env:
          # Use 'fake' environment variables since we're just checking syntax
          ENVIRONMENT_NAME: dev

      - name: Validate Prometheus Config
        run: |
          ./install_prometheus.sh
          ./promtool check config prometheus.yml
        working-directory: ./prometheus
