---
name: Deploy Prometheus

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths:
      - 'prometheus/**'
      - '.github/workflows/deploy-prometheus.yaml'
      - '!**.md'  # Ignore all markdown files in the repository
  release:
    types: [released]

jobs:
  check-config:
    uses: 18F/identity-idva-monitoring/.github/workflows/check-config.yaml@main

  deploy:
    if: github.repository_owner == '18F'
    runs-on: ubuntu-latest
    needs: check-config
    steps:
      - uses: actions/checkout@v2

      - uses: 18F/identity-idva-cf-setup@v2
        id: cf-setup
        with:
          cf-username: ${{ secrets.CF_USERNAME }}
          cf-password: ${{ secrets.CF_PASSWORD }}
          cf-org: ${{ secrets.CF_ORG }}

      - name: Deploy Prometheus
        run: cf push --vars-file vars.yaml
          --var ENVIRONMENT_NAME=${{ steps.cf-setup.outputs.target-environment }}
          --strategy rolling
        working-directory: ./prometheus

      - name: Apply CF Network Policies
        run: |
          cf add-network-policy prometheus alertmanager
          cf add-network-policy prometheus cf-metrics
          cf add-network-policy prometheus redis-metrics
          cf add-network-policy prometheus elasticsearch-metrics
          cf add-network-policy prometheus kong --port 8100 --protocol tcp
          cf add-network-policy prometheus watchtower
