---
name: Deploy Analytics Scripting

on:
  push:
    branches:
      - main
    paths:
      - analytics-scripting/analytics_script.py

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: 18F/identity-idva-cf-setup@v2
        with:
          cf-username: ${{ secrets.CF_USERNAME }}
          cf-password: ${{ secrets.CF_PASSWORD }}
          cf-org: ${{ secrets.CF_ORG }}

      - name: Create task for analytics scripting
        run: |
          cd analytics-scripting 
          cf push --task
