---
name: Deploy Grafana

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths:
      - 'grafana/**'
      - '.github/workflows/deploy-grafana.yaml'
      - '!**.md'  # Ignore all markdown files in the repository
  release:
    types: [released]

jobs:
  checkout-and-setup-cf:
    uses: 18F/identity-idva-monitoring/.github/workflows/checkout-and-setup-cf.yaml@main

  deploy:
    if: github.repository_owner == '18F'
    runs-on: ubuntu-latest
    needs: checkout-and-setup-cf
    steps:
      - name: Deploy Grafana
        run: cf push
          --var ENVIRONMENT_NAME=${{ steps.cf-setup.outputs.target-environment }}
          --var GRAFANA_PASS=${{ secrets.GRAFANA_PASS }}
          --strategy rolling
        working-directory: ./grafana

      - name: Apply CF Network Policies
        run: |
          cf add-network-policy grafana prometheus
          cf add-network-policy prometheus grafana
