---
name: Deploy Cortex

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths:
      - 'cortex/**'
      - '.github/workflows/deploy-cortex.yaml'
      - '!**.md'  # Ignore all markdown files in the repository
  release:
    types: [released]

jobs:
  checkout-and-setup-cf:
    uses: 18F/identity-idva-monitoring/.github/workflows/checkout-and-setup-cf.yaml@main

  deploy:
    if: github.repository_owner == '18F'
    runs-on: ubuntu-latest
    needs: checkout-and-setup-cf
    steps:
      - name: Deploy Cortex
        run: cf push --vars-file vars.yaml
          --var ENVIRONMENT_NAME=${{ steps.cf-setup.outputs.target-environment }}
          --strategy rolling
        working-directory: ./cortex

      - name: Apply CF Network Policies
        run: |
          cf add-network-policy prometheus cortex
          cf add-network-policy grafana cortex
