---
name: Deploy Cron

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths:
      - 'cron/**'
      - '.github/workflows/deploy-cron.yaml'
      - '!**.md'  # Ignore all markdown files in the repository
  release:
    types: [released]

jobs:
  deploy:
    if: github.repository_owner == 'GSA-TTS'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: GSA-TTS/identity-idva-cf-setup@v2
        id: cf-setup
        with:
          cf-username: ${{ secrets.CF_USERNAME }}
          cf-password: ${{ secrets.CF_PASSWORD }}
          cf-org: ${{ secrets.CF_ORG }}

      - name: Install Cron
        run: ./install_cron.sh
        working-directory: ./cron

      - name: Deploy cron
        run: cf push --strategy rolling
        working-directory: ./cron

      - name: Add network policies
        run: |
          cf add-network-policy cron outbound-proxy -s ${{ steps.cf-setup.outputs.target-environment }}-public --protocol tcp --port 8080
