---
name: Deploy Redis

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths:
      - 'redis/**'
      - '.github/workflows/deploy-redis.yaml'
      - '!**.md'  # Ignore all markdown files in the repository
  release:
    types: [released]

jobs:
  deploy:
    if: github.repository_owner == 'GSA-TTS'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: GSA-TTS/identity-idva-cf-setup@v2
        id: cf-setup
        with:
          cf-username: ${{ secrets.CF_USERNAME }}
          cf-password: ${{ secrets.CF_PASSWORD }}
          cf-org: ${{ secrets.CF_ORG }}

      - name: Install Redis Exporter
        run: ./install_redis_exporter.sh
        working-directory: ./redis

      - name: Deploy Redis Exporter
        run: cf push
          --vars-file vars.yaml
          --var ENVIRONMENT_NAME=${{ steps.cf-setup.outputs.target-environment }}
          --strategy rolling
        working-directory: ./redis
