---
name: Run Analytics Scripting

on:
  schedule:
  - cron: */5 * * * *

jobs:
  deploy:
    if: github.repository_owner == '18F'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: 18F/identity-idva-cf-setup@v2
        with:
          cf-username: ${{ secrets.CF_USERNAME }}
          cf-password: ${{ secrets.CF_PASSWORD }}
          cf-org: ${{ secrets.CF_ORG }}

      - name: Run task for analytics scripting
        run: |
          cd kibana/analytics-scripting 
          cf run-task kibana --name analytics-scripting
