---
name: Deploy Cortex

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths:
      - 'cortex/**'
      - '.github/workflows/deploy-cortex.yaml'
      - '!**.md'  # Ignore all markdown files in the repository
  release:
    types: [released]

jobs:
  deploy:
    if: github.repository_owner == '18F'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: 18F/identity-idva-cf-setup@v2
        id: cf-setup
        with:
          cf-username: ${{ secrets.CF_USERNAME }}
          cf-password: ${{ secrets.CF_PASSWORD }}
          cf-org: ${{ secrets.CF_ORG }}
          space-suffix: "-public"

      - name: Install Cortex
        run: ./install_cortex.sh
        working-directory: ./cortex

      - name: Deploy Cortex
        run: cf push --vars-file vars.yaml
          --var ENVIRONMENT_NAME=${{ steps.cf-setup.outputs.target-environment }}
          --strategy rolling
        working-directory: ./cortex

      - name: Apply CF Network Policies
        run: |
          closed_space=${{ steps.cf-setup.outputs.target-environment }}-closed
          public_space=${{ steps.cf-setup.outputs.target-environment }}-public

          # Apps that need to communicate to cortex are in closed space
          cf target -s "$closed_space"
          cf add-network-policy prometheus cortex -s "$public_space"
          cf add-network-policy grafana cortex -s "$public_space"
