name: Python Lint - Black

on:
  push:
    paths:
      - '**.py'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
